package Countries;

import java.awt.*;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 * EditCountry.java
 * A class representing the EditCountry form used in a maintaining countries database.
 * <pre>
 *   Project     <b>OperasGUI Database</b>
 *   Description This program provides database management for the countries. 
 *               It has the capability to add country
 *   Platform    Java(TM) SE Runtime Environment 1.8.0_151
 *   System      Windows 10 version 
 *   Course      <i>CS 142 Winter 2018</i>
 * </pre>
 *
 * @author:	Sanyapoom Sirijirakarn and Quynh Duc Vu
 * @version: 	1.00
 */
public class EditCountry extends javax.swing.JDialog {

    private Country newCountry;
    private boolean error = false;
    private String errorMessage = "";
    private final double MAX_POPULATION = 2000000000;
    private final Color white = Color.WHITE;
    private final Color pink = Color.PINK;
    ImageIcon countryFlag = null;
    String flagName = "";
    private boolean flagExist = false;
        /*
     * Method: EditCountry
     * Description: This is a default constructor for AddCountry
     * Environment: PC, Windows 10, NetBeans 8.0, jdk 1.8.0_144
     * Date: 2/9/2018
     * @parem void
     * @return void
     * @author Sanyapoom Sirijirakarn and Quynh Duc Vu
     * @version 1.0.0
     */ 
    public EditCountry() {
        initComponents();
        this.getRootPane().setDefaultButton(saveJButton);
        setLocationRelativeTo(null);
        nameJTextField.requestFocus();
        newCountry = null;
        setAlwaysOnTop(true);
        setModal(true);
    }
    /*
     * Method: EditCountry(java.awt.Frame parent, boolean modal)
     * Description: This is a overload constructor for AddCountry
     * Environment: PC, Windows 10, NetBeans 8.0, jdk 1.8.0_144
     * Date: 2/9/2018
     * @parem java.awt.Frame parent, boolean modal
     * @return void
     * @author Sanyapoom Sirijirakarn and Quynh Duc Vu
     * @version 1.0.0
     */ 
    public EditCountry(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    /*
     * Method: EditCountry(Country country)
     * Description: This is a overload constructor for EditCountry
     * Environment: PC, Windows 10, NetBeans 8.0, jdk 1.8.0_144
     * Date: 2/9/2018
     * @parem country
     * @return void
     * @author Sanyapoom Sirijirakarn and Quynh Duc Vu
     * @version 1.0.0
     */ 
    public EditCountry(Country country)
    {
        this(); //call default constructor
        nameJTextField.setText(country.getName());
        countryPopJTextField.setText(String.valueOf(country.getCountryPop()));
        capitalJTextField.setText(country.getCapital());
        capitalPopJTextField.setText(String.valueOf(country.getCapitalPop()));
        sizeJTextField.setText(String.valueOf(country.getSize()));
        locationJTextField.setText(country.getLocation());
        languageJTextField.setText(country.getLanguage());
        riverJTextField.setText(country.getRiver());
        nameJTextField.requestFocus();
    }
    /*
     * Method: Country getCountry()
     * Description: This is a class to return new country
     * Environment: PC, Windows 10, NetBeans 8.0, jdk 1.8.0_144
     * Date: 2/9/2018
     * @parem void
     * @return void
     * @author Sanyapoom Sirijirakarn and Quynh Duc Vu
     * @version 1.0.0
     */ 
    public Country getCountry(){
        return newCountry;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleJPanel = new javax.swing.JPanel();
        picJLabel = new javax.swing.JLabel();
        titleJLabel = new javax.swing.JLabel();
        infoJPanel = new javax.swing.JPanel();
        nameJLabel = new javax.swing.JLabel();
        nameJTextField = new javax.swing.JTextField();
        countryPopJLabel = new javax.swing.JLabel();
        countryPopJTextField = new javax.swing.JTextField();
        capitalJLabel = new javax.swing.JLabel();
        capitalJTextField = new javax.swing.JTextField();
        capitalPopJLabel = new javax.swing.JLabel();
        capitalPopJTextField = new javax.swing.JTextField();
        sizeJLabel = new javax.swing.JLabel();
        sizeJTextField = new javax.swing.JTextField();
        locationLabel = new javax.swing.JLabel();
        locationJTextField = new javax.swing.JTextField();
        languageJLabel = new javax.swing.JLabel();
        languageJTextField = new javax.swing.JTextField();
        riverJLabel = new javax.swing.JLabel();
        riverJTextField = new javax.swing.JTextField();
        flagJLabel = new javax.swing.JLabel();
        flagJButton = new javax.swing.JButton();
        controlJPanel = new javax.swing.JPanel();
        saveJButton = new javax.swing.JButton();
        cancelJButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        titleJPanel.setPreferredSize(new java.awt.Dimension(496, 85));

        picJLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Countries/pic.jpg"))); // NOI18N

        titleJLabel.setFont(new java.awt.Font("Elephant", 3, 36)); // NOI18N
        titleJLabel.setForeground(new java.awt.Color(0, 102, 204));
        titleJLabel.setText("Edit Country");

        javax.swing.GroupLayout titleJPanelLayout = new javax.swing.GroupLayout(titleJPanel);
        titleJPanel.setLayout(titleJPanelLayout);
        titleJPanelLayout.setHorizontalGroup(
            titleJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titleJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(picJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(titleJLabel)
                .addContainerGap(13, Short.MAX_VALUE))
        );
        titleJPanelLayout.setVerticalGroup(
            titleJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titleJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(titleJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titleJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(picJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        getContentPane().add(titleJPanel, java.awt.BorderLayout.PAGE_START);

        infoJPanel.setLayout(new java.awt.GridLayout(9, 0, 0, 2));

        nameJLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nameJLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        nameJLabel.setText("Country Name: ");
        infoJPanel.add(nameJLabel);

        nameJTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nameJTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                nameJTextFieldFocusLost(evt);
            }
        });
        infoJPanel.add(nameJTextField);

        countryPopJLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        countryPopJLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        countryPopJLabel.setText("Country Population(in millions): ");
        infoJPanel.add(countryPopJLabel);

        countryPopJTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        countryPopJTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                countryPopJTextFieldFocusLost(evt);
            }
        });
        infoJPanel.add(countryPopJTextField);

        capitalJLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        capitalJLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        capitalJLabel.setText("Capital City: ");
        infoJPanel.add(capitalJLabel);

        capitalJTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        capitalJTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                capitalJTextFieldFocusLost(evt);
            }
        });
        infoJPanel.add(capitalJTextField);

        capitalPopJLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        capitalPopJLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        capitalPopJLabel.setText("Capital Population(in millions): ");
        infoJPanel.add(capitalPopJLabel);

        capitalPopJTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        capitalPopJTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                capitalPopJTextFieldFocusLost(evt);
            }
        });
        infoJPanel.add(capitalPopJTextField);

        sizeJLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        sizeJLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        sizeJLabel.setText("Size(in square miles): ");
        infoJPanel.add(sizeJLabel);

        sizeJTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        sizeJTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                sizeJTextFieldFocusLost(evt);
            }
        });
        infoJPanel.add(sizeJTextField);

        locationLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        locationLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        locationLabel.setText("Location(Continent): ");
        infoJPanel.add(locationLabel);

        locationJTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        locationJTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                locationJTextFieldFocusLost(evt);
            }
        });
        infoJPanel.add(locationJTextField);

        languageJLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        languageJLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        languageJLabel.setText("Main Language: ");
        infoJPanel.add(languageJLabel);

        languageJTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        languageJTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                languageJTextFieldFocusLost(evt);
            }
        });
        infoJPanel.add(languageJTextField);

        riverJLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        riverJLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        riverJLabel.setText("Largest River: ");
        infoJPanel.add(riverJLabel);

        riverJTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        riverJTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                riverJTextFieldFocusLost(evt);
            }
        });
        infoJPanel.add(riverJTextField);

        flagJLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        flagJLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        flagJLabel.setText("Flag: ");
        infoJPanel.add(flagJLabel);

        flagJButton.setBackground(new java.awt.Color(204, 255, 204));
        flagJButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        flagJButton.setMnemonic('s');
        flagJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                flagJButtonActionPerformed(evt);
            }
        });
        infoJPanel.add(flagJButton);

        getContentPane().add(infoJPanel, java.awt.BorderLayout.CENTER);

        controlJPanel.setLayout(new java.awt.GridLayout(1, 2, 5, 5));

        saveJButton.setBackground(new java.awt.Color(204, 255, 204));
        saveJButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        saveJButton.setMnemonic('s');
        saveJButton.setText("Save");
        saveJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveJButtonActionPerformed(evt);
            }
        });
        controlJPanel.add(saveJButton);

        cancelJButton.setBackground(new java.awt.Color(204, 255, 204));
        cancelJButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cancelJButton.setMnemonic('c');
        cancelJButton.setText("Cancel");
        cancelJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelJButtonActionPerformed(evt);
            }
        });
        controlJPanel.add(cancelJButton);

        getContentPane().add(controlJPanel, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Method: nameJTextFieldFocusLost (java.awt.event.ActionEvent evt)
     * Description: This is a class to check name is valid
     * Environment: PC, Windows 10, NetBeans 8.0, jdk 1.8.0_144
     * Date: 2/9/2018
     * @parem void
     * @return void
     * @author Sanyapoom Sirijirakarn and Quynh Duc Vu
     * @version 1.0.0
     */
    private void nameJTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameJTextFieldFocusLost
        String input = nameJTextField.getText();
        if (Validation.isValidName(input)) {
            nameJTextField.setBackground(white);
        } else {
            nameJTextField.setBackground(pink);
        }
    }//GEN-LAST:event_nameJTextFieldFocusLost
    /**
     * Method: countryPopJTextFieldFocusLost (java.awt.event.ActionEvent evt)
     * Description: This is a class to check country population is valid
     * Environment: PC, Windows 10, NetBeans 8.0, jdk 1.8.0_144
     * Date: 2/9/2018
     * @parem void
     * @return void
     * @author Sanyapoom Sirijirakarn and Quynh Duc Vu
     * @version 1.0.0
     */
    private void countryPopJTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_countryPopJTextFieldFocusLost
        String input = countryPopJTextField.getText();
        if (Validation.isDouble(input)) {
            countryPopJTextField.setBackground(white);
        } else {
            countryPopJTextField.setBackground(pink);
        }
    }//GEN-LAST:event_countryPopJTextFieldFocusLost
    /**
     * Method: capitalJTextFieldFocusLost (java.awt.event.ActionEvent evt)
     * Description: This is a class to check capital is valid
     * Environment: PC, Windows 10, NetBeans 8.0, jdk 1.8.0_144
     * Date: 2/9/2018
     * @parem void
     * @return void
     * @author Sanyapoom Sirijirakarn and Quynh Duc Vu
     * @version 1.0.0
     */
    private void capitalJTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_capitalJTextFieldFocusLost
        String input = capitalJTextField.getText();
        if (Validation.isValidName(input)) {
            capitalJTextField.setBackground(white);
        } else {
            capitalJTextField.setBackground(pink);
        }
    }//GEN-LAST:event_capitalJTextFieldFocusLost
    /**
     * Method: capitalPopJTextFieldFocusLost (java.awt.event.ActionEvent evt)
     * Description: This is a class to check capital population is valid
     * Environment: PC, Windows 10, NetBeans 8.0, jdk 1.8.0_144
     * Date: 2/9/2018
     * @parem void
     * @return void
     * @author Sanyapoom Sirijirakarn and Quynh Duc Vu
     * @version 1.0.0
     */
    private void capitalPopJTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_capitalPopJTextFieldFocusLost
        String input = capitalPopJTextField.getText();
        if (Validation.isDouble(input)) {
            capitalPopJTextField.setBackground(white);
        } else {
            capitalPopJTextField.setBackground(pink);
        }
    }//GEN-LAST:event_capitalPopJTextFieldFocusLost
    /**
     * Method: sizeJTextFieldFocusLost (java.awt.event.ActionEvent evt)
     * Description: This is a class to check size is valid
     * Environment: PC, Windows 10, NetBeans 8.0, jdk 1.8.0_144
     * Date: 2/9/2018
     * @parem void
     * @return void
     * @author Sanyapoom Sirijirakarn and Quynh Duc Vu
     * @version 1.0.0
     */
    private void sizeJTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_sizeJTextFieldFocusLost
        String input = sizeJTextField.getText();
        if (Validation.isInteger(input)) {
            sizeJTextField.setBackground(white);
        } else {
            sizeJTextField.setBackground(pink);
        }
    }//GEN-LAST:event_sizeJTextFieldFocusLost
    /**
     * Method: locationJTextFieldFocusLost (java.awt.event.ActionEvent evt)
     * Description: This is a class to check location is valid
     * Environment: PC, Windows 10, NetBeans 8.0, jdk 1.8.0_144
     * Date: 2/9/2018
     * @parem void
     * @return void
     * @author Sanyapoom Sirijirakarn and Quynh Duc Vu
     * @version 1.0.0
     */
    private void locationJTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_locationJTextFieldFocusLost
        // Need to channge validation (also in save button)
    }//GEN-LAST:event_locationJTextFieldFocusLost
    /**
     * Method: languageJTextFieldFocusLost (java.awt.event.ActionEvent evt)
     * Description: This is a class to check language is valid
     * Environment: PC, Windows 10, NetBeans 8.0, jdk 1.8.0_144
     * Date: 2/9/2018
     * @parem void
     * @return void
     * @author Sanyapoom Sirijirakarn and Quynh Duc Vu
     * @version 1.0.0
     */
    private void languageJTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_languageJTextFieldFocusLost
        String input = languageJTextField.getText();
        if (Validation.isValidName(input)) {
            languageJTextField.setBackground(white);
        } else {
            languageJTextField.setBackground(pink);
        }
    }//GEN-LAST:event_languageJTextFieldFocusLost
    /**
     * Method: riverJTextFieldFocusLost (java.awt.event.ActionEvent evt)
     * Description: This is a class to check river is valid
     * Environment: PC, Windows 10, NetBeans 8.0, jdk 1.8.0_144
     * Date: 2/9/2018
     * @parem void
     * @return void
     * @author Sanyapoom Sirijirakarn and Quynh Duc Vu
     * @version 1.0.0
     */
    private void riverJTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_riverJTextFieldFocusLost
        String input = riverJTextField.getText();
        if (Validation.isValidName(input)) {
            riverJTextField.setBackground(white);
        } else {
            riverJTextField.setBackground(pink);
        }
    }//GEN-LAST:event_riverJTextFieldFocusLost
    /**
     * Method: saveJButtonActionPerformed (java.awt.event.ActionEvent evt)
     * Description: This is a class to save country from JList
     * Environment: PC, Windows 10, NetBeans 8.0, jdk 1.8.0_144
     * Date: 2/9/2018
     * @parem void
     * @return void
     * @author Sanyapoom Sirijirakarn and Quynh Duc Vu
     * @version 1.0.0
     */
    private void saveJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveJButtonActionPerformed
        String name = "";
        float population = 0;
        String capital = "";
        float captialPop = 0;
        int size = 0;
        String location = "";
        String languague = "";
        String river = "";

        String countryName = nameJTextField.getText();
        String countryPopulation = countryPopJTextField.getText();
        String capitalCity = capitalJTextField.getText();
        String capitalPopulation = capitalPopJTextField.getText();
        String countrySize = sizeJTextField.getText();
        String contitent = locationJTextField.getText();
        String countryLanguage = languageJTextField.getText();
         String countryRiver = riverJTextField.getText();

        if (!Validation.isValidName(countryName)) {
            errorMessage += "Invalid Country Name\n";
            nameJTextField.requestFocus();
            error = true;
            nameJTextField.setToolTipText(nameJTextField.getToolTipText() + "--Invalid Country Name");
        } else if (!Validation.isDouble(countryPopulation, 0, MAX_POPULATION)) {
            errorMessage += "Invalid Population\n";
            countryPopJTextField.requestFocus();
            error = true;
            countryPopJTextField.setToolTipText(countryPopJTextField.getToolTipText() + "--Invalid Population");
        } else if (!Validation.isValidName(capitalCity)) {
            errorMessage += "Invalid Capital City Name\n";
            capitalJTextField.requestFocus();
            error = true;
            capitalJTextField.setToolTipText(capitalJTextField.getToolTipText() + "--Invalid Captial City Name");
        } else if (!Validation.isDouble(capitalPopulation, 0, MAX_POPULATION)) {
            errorMessage += "Invalid Capital City Population\n";
            capitalPopJTextField.requestFocus();
            error = true;
            capitalPopJTextField.setToolTipText(capitalPopJTextField.getToolTipText() + "--Invalid Capital City Population");
        } else if (!Validation.isInteger(countrySize)) {
            errorMessage += "Invalid Size\n";
            sizeJTextField.requestFocus();
            error = true;
            sizeJTextField.setToolTipText(sizeJTextField.getToolTipText() + "--Invalid Size");
        } else if (!Validation.isValidName(contitent)) {
            //change validation for location
            errorMessage += "Invalid Location\n";
            locationJTextField.requestFocus();
            error = true;
            locationJTextField.setToolTipText(locationJTextField.getToolTipText() + "--Invalid Location");
        } else if (!Validation.isValidName(countryLanguage)) {
            errorMessage += "Invalid Language\n";
            languageJTextField.requestFocus();
            error = true;
            languageJTextField.setToolTipText(languageJTextField.getToolTipText() + "--Invalid Language");
        } else if (!Validation.isValidName(countryRiver)) {
            errorMessage += "Invalid River Name\n";
            riverJTextField.requestFocus();
            error = true;
            riverJTextField.setToolTipText(riverJTextField.getToolTipText() + "--Invalid River Name");
        } else if (flagExist = true)
        {
            error = false;
        }
        if (!error) {
            try {
                name = nameJTextField.getText();
                population = Float.parseFloat(countryPopJTextField.getText());
                capital = capitalJTextField.getText();
                captialPop = Float.parseFloat(capitalPopJTextField.getText());
                size = Integer.parseInt(sizeJTextField.getText());
                location = locationJTextField.getText();
                languague = languageJTextField.getText();
                river = riverJTextField.getText();
                flagName = flagJButton.getText();
                
                newCountry = new Country(name, population, capital, captialPop, size, location, languague, river, countryFlag, flagName); 
                this.dispose();
            } catch (Exception exp) {
                throw new RuntimeException("Error parsing input");
            }
        }
    }//GEN-LAST:event_saveJButtonActionPerformed
    /**
     * Method: cancelJButtonActionPerformed (java.awt.event.ActionEvent evt)
     * Description: This is a class to close the form
     * Environment: PC, Windows 10, NetBeans 8.0, jdk 1.8.0_144
     * Date: 2/9/2018
     * @parem void
     * @return void
     * @author Sanyapoom Sirijirakarn and Quynh Duc Vu
     * @version 1.0.0
     */
    private void cancelJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelJButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelJButtonActionPerformed
    /**
     * Method: flagJButtonActionPerformed (java.awt.event.ActionEvent evt)
     * Description: This is a class to get picture of the flag
     * Environment: PC, Windows 10, NetBeans 8.0, jdk 1.8.0_144
     * Date: 2/9/2018
     * @parem void
     * @return void
     * @author Sanyapoom Sirijirakarn and Quynh Duc Vu
     * @version 1.0.0
     */
    private void flagJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_flagJButtonActionPerformed
        //Find Flag Image
        JFileChooser chooser = new JFileChooser("src/Images");
        int choice = chooser.showOpenDialog(null);
        int flagWidth = 429;
        int flagHeight = 251;
        if (choice == JFileChooser.APPROVE_OPTION)
        {
            File chosenFile = chooser.getSelectedFile();
            countryFlag = new ImageIcon("src/Countries/" + chosenFile.getName());
            flagJButton.setText(chosenFile.getName());
            Image image = countryFlag.getImage();  // transform it
            Image newImg = image.getScaledInstance(flagWidth, flagHeight, java.awt.Image.SCALE_SMOOTH); // scale it the smooth way
            countryFlag = new ImageIcon(newImg);
            flagExist = true;
        }
        else
        {
            JOptionPane.showMessageDialog(null, "File does not exist",
                    "File Input Error", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_flagJButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditCountry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditCountry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditCountry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditCountry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                EditCountry dialog = new EditCountry(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelJButton;
    private javax.swing.JLabel capitalJLabel;
    private javax.swing.JTextField capitalJTextField;
    private javax.swing.JLabel capitalPopJLabel;
    private javax.swing.JTextField capitalPopJTextField;
    private javax.swing.JPanel controlJPanel;
    private javax.swing.JLabel countryPopJLabel;
    private javax.swing.JTextField countryPopJTextField;
    private javax.swing.JButton flagJButton;
    private javax.swing.JLabel flagJLabel;
    private javax.swing.JPanel infoJPanel;
    private javax.swing.JLabel languageJLabel;
    private javax.swing.JTextField languageJTextField;
    private javax.swing.JTextField locationJTextField;
    private javax.swing.JLabel locationLabel;
    private javax.swing.JLabel nameJLabel;
    private javax.swing.JTextField nameJTextField;
    private javax.swing.JLabel picJLabel;
    private javax.swing.JLabel riverJLabel;
    private javax.swing.JTextField riverJTextField;
    private javax.swing.JButton saveJButton;
    private javax.swing.JLabel sizeJLabel;
    private javax.swing.JTextField sizeJTextField;
    private javax.swing.JLabel titleJLabel;
    private javax.swing.JPanel titleJPanel;
    // End of variables declaration//GEN-END:variables
}
